### ISSUE TITLE
AVAE Baseline Code in Experiments

### ISSUE THREAD

**Issue by luotianze** [data-iitd/proactive#1]
In the experiments you have reported the results for baseline AVAE published in CVPR 2019. But the implementation of that paper is not public. I have mailed the authors for it but they have yet to reply to my emails. 

Can you please share the code the authors have shared with you? Thank you very much in advance.

**Comment by gvinayak** [comment]
Hi @luotianze,
Thanks a lot for your interest in our work. 

We had also mailed the authors of the CVPR paper to share their code; however, we did not receive any reply. Thus, we created the baseline code ourselves by plugging in a VAE over an RNN-based point process. You can refer to the implementation of our AISTATS paper, which already has a similar setup[1]. Anyways, if you want me to share our implementation of AVAE, please let me know. 

Thanks a lot,
VG

[1] https://github.com/data-iitd/imtpp

**Comment by gvinayak** [comment]
Hi @luotianze,
Please let me know if you want the code, so that I can close this issue.

**Comment by gvinayak** [comment]
Closing due to no recent activities.
